### ISSUE TITLE
Start using app.json for Fourchette instead of forking?

### ISSUE THREAD

**Issue by jipiboily** [rainforestapp/fourchette#38]
I think it would make more sense (at least to us) not to fork an app but instead use app.json to create a new app, and seed our database ourselves.

I am not sure how many people rely on Fourchette and the fact that it is forking apps vs the number of people who would be fine using app.json?

Yes, we could support both, maybe it's not worth it though.

Thoughts?

/cc @smathieu @ukd1 @markpundsack @friism @bdarfler

**Comment by seanknox** [comment]
I vote for `app.json`. The main drawback against `forky`/forking is that it's unable to accommodate migrations. Example: 

1. Developer pushes up feature branch with migrations.
2. `forky` forks a Heroku app (say, some app running `master`) to create the new acceptance/testing app
3. A new slug is build using the feature branch tarball. At some point it finishes, but there's no callback to know when.
4. Without a callback or synchronous build process, there's no way to run post-deploy tasks like `rake db:migrate`.

**Comment by jipiboily** [comment]
@seanknox there is a hacky way to do that though, you can watch for the build and as long as it's not done, sleep X seconds and try again. This is hacky, but this is what I did...it's awful, but here it is: https://github.com/rainforestapp/rf-ourchette/blob/master/lib/fourchette/callbacks.rb#L80

**Comment by jipiboily** [comment]
FYI, we just decided to deprecate Fourchette. You can (and probably should) use the Heroku review apps instead which was inspired by Fourchette. 

https://devcenter.heroku.com/articles/github-integration-review-apps

Thanks!

**Comment by seanknox** [comment]
:crying_cat_face: @jipiboily We did the same thing with our project that was inspired by Fourchette. Thanks for providing this in the first place, it's been an incredible help!

**Comment by friism** [comment]
Thanks also from Heroku!

Fourchette showed us what could be done and was a great inspiration.
Michael

**Comment by ukd1** [comment]
@friism @seanknox <3

**Comment by jipiboily** [comment]
Much :heart: @friism & @seanknox. Was a fun ride :grinning:
