### ISSUE TITLE
Pull code directly from GitHub

### ISSUE THREAD

**Issue by markpundsack** [rainforestapp/fourchette#41]
It looks like fourchette currently pulls down the GitHub repo and then uploads it to the Heroku Build API, but the build API supports grabbing the tarball directly from GitHub. For private repos, you could use GitHub's temporary authenticated archive link:

https://developer.github.com/v3/repos/contents/#get-archive-link

/cc @friism

**Comment by jipiboily** [comment]
FYI, we just decided to deprecate Fourchette. You can (and probably should) use the Heroku review apps instead which was inspired by Fourchette. 

https://devcenter.heroku.com/articles/github-integration-review-apps

Thanks!
