### ISSUE TITLE
Time for 1.0

### ISSUE THREAD

**Issue by jipiboily** [rainforestapp/fourchette#53]
This should have been done before, but I think Fourchette should have been 1.0+ for a "long time" now...

Thoughts?

**Comment by scruti** [comment]
I would go for it. We're using it intensively and I was even surprised when saw that it's still in 0.x version.

**Comment by jipiboily** [comment]
@scruti did you face any other bugs recently?

**Comment by scruti** [comment]
Just yesterday pgbackup addon copy started failing. Seems that the addon disappeared from Heroku's addon list :-S
Issue opened by another dev here: https://github.com/rainforestapp/fourchette/issues/56

**Comment by jipiboily** [comment]
FYI, we just decided to deprecate Fourchette. You can (and probably should) use the Heroku review apps instead which was inspired by Fourchette. 

https://devcenter.heroku.com/articles/github-integration-review-apps

Thanks!
