### ISSUE TITLE
After release of Review Apps functionality this project is almost obsolete?

### ISSUE THREAD

**Issue by skatkov** [rainforestapp/fourchette#58]
While trying to roll out fourchette solution for a company i work in, i've found out that heroku has released Review App functionality (currently in Beta).
https://blog.heroku.com/archives/2015/5/19/heroku_review_apps_beta

It appears, that this project will become obsolete once this functionality will become stable?

**Comment by jipiboily** [comment]
FYI, we just decided to deprecate Fourchette. You can (and probably should) use the Heroku review apps instead which was inspired by Fourchette. 

https://devcenter.heroku.com/articles/github-integration-review-apps

Thanks!
